### ISSUE TITLE
Copy blobs from some storage account into a new asset in a AMS account

### ISSUE THREAD

**Issue by himadrinath** [Azure-Samples/media-services-dotnet-functions-integration#24]
@xpouyat  i am trying to Copy blobs from some storage account into a new asset in a AMS account in azure function do u have any example links..

like this one: https://docs.microsoft.com/en-us/azure/media-services/media-services-copying-existing-blob

**Comment by xpouyat** [comment]
Hi,
Sure. From a logic app, you can call
start-blob-copy-to-asset
then
check-blob-copy-to-asset-status
then
sync-asset.
These functions are in https://github.com/Azure-Samples/media-services-dotnet-functions-integration/tree/master/media-functions-for-logic-app

**Comment by himadrinath** [comment]
@xpouyat Thank you  👍
