### ISSUE TITLE
How to index to multiple languages?

### ISSUE THREAD

**Issue by CarlosOnline** [Azure-Samples/media-services-dotnet-functions-integration#33]
Can transcription be done to multiple languages at a time?

If so what is the schema for that?

https://github.com/Azure-Samples/media-services-dotnet-functions-integration/blob/master/100-basic-encoding/presets/Indexerv2.json

**Comment by xpouyat** [comment]
You would need to use a V3 transform with several output.
https://docs.microsoft.com/en-us/rest/api/media/transforms/createorupdate#audioanalyzerpreset
